[package]
name = "motex"
version = "0.1.0"
authors = ["Parker Burnett <jpburnett@byu.net>"]
edition = "2021"
rust-version = "1.70"
publish = false

[dependencies]
eframe = { version = "0.23.0", features = ["persistence"] }
env_logger = "0.10"
variant_count = "1.1"
image = "0.24.7"
anyhow = "1.0.72"
byteorder = "1.4.3"