[package]
name = "motex"
version = "0.1.0"
authors = ["Parker Burnett <jpburnett@byu.net>"]
edition = "2021"
rust-version = "1.70"
publish = false
readme = "README.md"

[dependencies]
eframe = { version = "0.24.1", features = ["persistence"] }
egui-modal = "0.3.0"
egui-phosphor = "0.3.1"
env_logger = "0.10"
variant_count = "1.1"
image = "0.24.7"
anyhow = "1.0.75"
byteorder = "1.4.3"
rfd = "0.12.1"